### ISSUE TITLE
Investigate about kernel issues on fedora (21?)

### ISSUE THREAD

**Issue by moul** [online-labs/image-fedora#13]
`pisto` on IRC encountered problem(s) to get fedora 21 working with current kernels

Does anyone have information about specific kernel needs for fedora (21) ?

I'm not a fedora guru at all and need more details

**Comment by pisto** [comment]
So, worked more on this.
fedup fails because it expects a kernel to be actually there. I think this can be cataloged as a fedup bug.

I updated with the yum method, and it seems it works. However, any systemd update will override your reboot target, where you have that unholy hack (no insult) to reboot the machine. I think that thing you have there is hardly the right way to go, but I don't know systemd and I cannot help you there. Also, powering off needs the same thing.

yum likes to crash with random pointers being freed. I have no idea why this happens, but it's very likely to trash your system soon. This needs to be fixed.

Besides this, I believe that afterall fedora might work well without a kernel in /boot.

**Comment by aimxhaisse** [comment]
@pisto: Yes, that's exactly why we need that unmount thing, we have to properly close the NBD connection at reboot, otherwise the server will be stucked at boot, waiting for being able to re-establish a connection. Also, the order of shutdown is slightly different than in 'classic' systems, which generally stop services, then unmount /, we can't do this here, since stopping nbd will make / unavailable and the system crash. This disconnection has to be the very last thing done.

I think we can survive updates if we properly implement this in /etc and not in /usr/lib/systemd... I'm opening a ticket on this.

Concerning the random crashes of yum, it sucks, we haven't figured out what the issue was.

**Comment by pisto** [comment]
The problem of replacing that unit file is that the original command doesn't simply reboot the machine. From the man page of systemctl: "When used with halt, poweroff, reboot or kexec, execute the selected operation without shutting down all units. However, all processes will be killed forcibly and all file systems are unmounted or remounted read-only". You should replicate this in details if you really want to replace the unit file.

Also, what if the kernel crashes? And what in the case of kexec (which could be a loophole to let the user boot his own kernel)? In my opinion you should solve this problem in the host. Have your virtualization software send a signal when it detects that the guest reboots, and forcibly reset the connection.

On another topic, I believe that you shouldn't touch defaults of a distro. The user expects them to be similar to normal installations of the OS (if he chooses a particular distro it's because he knows it and expects certain defaults). I would really like that this image didn't disable the tmpfs /tmp, nor mess with the sshd config file.

**Comment by aimxhaisse** [comment]
Thanks for you comment!

Unfortunately, I don't think we can have a "kill all services, *then* remount in read-only" strategy here, there is no possible "then" because after killing NBD, / is down, we can't execute any command without getting a kernel panic. We are in a situation where the filesystem depends on a service. So what we try to do is let the classic shutdown sequence go on, and once all services except NBD are killed, instead of remounting in read-only and shutdown, we kill NBD and shutdown. This implies a hack (we have to rename xnbd-client as @xnbd-client so it's not considered as a service and killed by systemd). We haven't found a standard way to do this in all distributions, which explains why it's hacky (if you find betters ways to do it, we'd eagerly integrate it!).

If the kernel crashes, the server somehow has to be 'hard-reboot' manually (via the console), this 'hard-reboot' action ensures the NBD connection is properly reset.

Regarding modifications on the distributions, we do them mainly to have something that fits our infrastructure (DNS, ...), so most users can start using them without need of customizations (applications like Wordpress are based on these base distrubutions). Advanced users can still tweak the distributions or even roll their own from scratch. We are thinking on ways to properly package modifications we do (via .deb and rpm).

**Comment by pisto** [comment]
Regarding yum, I haven't had any crash (as of yet) after upgrading to Fedora 21. Fedora users are generally enthusiasts about new things, so probably it doesn't matter if you would offer Fedora 21 only.

**Comment by moul** [comment]
Ok nice, did you upgrade to fedora 21 from fedora 20 or did you installed fedora 21 on a secondary volume ?
Do you have a how-to link or the commands to use to upgrade to fedora 21 ?

For you information, we are using fedora 20, because, it's the only official pre-build image found for armhf:
http://fedora.mirrors.ovh.net/linux/updates/20/Images/armhfp/Fedora-Minimal-armhfp-20-20140407-sda.raw.xz

I would love to upgrade the image to 21 and trash the buggy 20 :)

**Comment by moul** [comment]
I'm trying a new build with this base: http://fedora.mirrors.ovh.net/linux/releases/21/Images/armhfp/Fedora-Minimal-armhfp-21-5-sda.raw.xz
But I'm still interested by the 20->21 upgrade instructions

**Comment by pisto** [comment]
https://fedoraproject.org/wiki/Upgrading_Fedora_using_yum#Fedora_20_-.3E_Fedora_21

The first instruction fails, the filename is /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-21-armhfp

**Comment by kwizart** [comment]
FYI, here it the fedora upstream kernel config git module:
http://pkgs.fedoraproject.org/cgit/kernel.git/tree/
The armhfp is built using the  following config files:
config-generic
config-arm-generic
config-armv7-generic

**Comment by kwizart** [comment]
(and http://pkgs.fedoraproject.org/cgit/kernel.git/tree/config-armv7)
I would suggest to try the fedora kernel directly with nolp built separatly:

Or trying to recompute the diff between mvbe_v7_deconfig and the fedora config, and sorting the CONFIG options relevant to a kernel feature from the ones that would be unrelevant to the hardware. I would suggest to enable the following: (not sure if theses ERRATA really apply to the C1).

+CONFIG_AUDIT=y

+CONFIG_ARM_ERRATA_430973=y (seems related to cortext a8)
+CONFIG_ARM_ERRATA_643719=y (some cortex a9)

+CONFIG_FANOTIFY=y
+CONFIG_FANOTIFY_ACCESS_PERMISSIONS=y

+CONFIG_AUTOFS4_FS=y

+CONFIG_SECCOMP=y
+CONFIG_SECURITY=y
+CONFIG_SECURITY_NETWORK=y
+CONFIG_SECURITY_NETWORK_XFRM=y
+CONFIG_SECURITY_SELINUX=y
+CONFIG_SECURITY_SELINUX_BOOTPARAM=y
+CONFIG_SECURITY_SELINUX_DISABLE=y
+CONFIG_TMPFS_POSIX_ACL=y
+CONFIG_TMPFS_XATTR=y

+CONFIG_FSCACHE_STATS=y
+CONFIG_FSCACHE_OBJECT_LIST=y
+CONFIG_CACHEFILES=m

Others config options might be needed, but a good doc would be the /usr/share/doc/systemd/README

This one might be needed for firewalld, at least.
+CONFIG_BRIDGE_NF_EBTABLES=m

Thx

**Comment by moul** [comment]
Thank you for your feedback, we will build a kernel with all those things and come back to you
Thanks again @kwizart and @pisto

**Comment by moul** [comment]
@kwizart just build a kernel following your requirements (not the default config for now): https://github.com/online-labs/kernel-config/issues/37#issuecomment-75283991

**Comment by pisto** [comment]
It seems that anything but 3.17 119 fails badly for me. It even got into "transferring data (reboot fail, halting node)" state. I get no serial console, so I have no idea what's happening.

**Comment by moul** [comment]
I will give a look, it sounds strange

**Comment by pisto** [comment]
edouardb told me it was some unrelated issues with "message passing".

**Comment by moul** [comment]
Ok, I'm closing this issue, now we can continue on the dedicated issue on kernel-config: https://github.com/online-labs/kernel-config/issues/37

You can also open new kernel-related issues on the same project
